[pytest]
testpaths = validacion_horizontal
markers =
    suite_flujo_residente: Suite Flujo Residente
    dc_ingreso: DolphinCollection Ingreso (EUV_01, EUV_02)
    dc_postulacion: DolphinCollection PostulacionAConvocatoria (EUV_03-EUV_09)
    euv01: Ingreso con credenciales correctas
    euv02: Intento de ingreso con credenciales incorrectas
    euv03: Postulacion normal con verificacion
    euv04: Intento de postulacion con postulacion activa
    euv05: Intento con archivo de formato erroneo
    euv06: Intento con archivo muy pesado
    euv07: Intento con archivos incompletos
    euv08: Intento antes de carga de archivos
    euv09: Postulacion usando todos los tooltips
addopts = -v --tb=short
